base: /
dest: ../docs
title: yobot
description: 公主链接群聊机器人
head:
  - [link, { rel: "icon", href: "/logo/logo.ico" }]
  - [link, { rel: "apple-touch-icon", href: "/logo/logo.ico" }]
themeConfig:
  logo: /logo/logo.png
  search: false
  smoothScroll: true
  nav:
    - text: 首页
      link: /
    - text: 安装方法
      link: /install/cq/
    - text: 功能列表
      link: /features/
    - text: 高级
      items:
      - text: 开启Web模式
        link: /usage/web-mode/
      - text: Web模式 - 公会战
        link: /usage/web-clanbattle/
    - text: 源码
      items:
        - text: GitHub
          link: https://github.com/yuudi/yobot
        - text: Gitee
          link: https://gitee.com/yobot/yobot
    - text: 关于
      link: /about/
plugins:
  - - vuepress-plugin-clean-urls
    - normalSuffix: "/"
      indexSuffix: "/"
      notFoundPath: "/404.html"
